version: "3.8"

networks:
  rede:
    driver: bridge

services:
  node:
    build:
      context: ./api
      target: DEV
    container_name: node
    volumes:
      - ./api:/app
    ports:
      - 3000:3000
    networks:
      - rede
